import { EntityRegistry, type EntityConfig, type FieldMeta } from '../_base/index.js';
import { AuditLogSchema, CreateAuditLogSchema, UpdateAuditLogSchema } from './schemas.js';

const fields: FieldMeta[] = [
  {
    key: 'id',
    label: 'Id',
    type: 'str',
    nullable: false,
    is_auto: true,
    is_primary_key: true,
    filterable: true,
    has_foreign_key: false,
    field_type: 'text',
  },
  {
    key: 'table_name',
    label: 'Table Name',
    type: 'str',
    nullable: false,
    is_auto: false,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'text',
  },
  {
    key: 'record_id',
    label: 'Record Id',
    type: 'str',
    nullable: false,
    is_auto: false,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'text',
  },
  {
    key: 'action',
    label: 'Action',
    type: 'str',
    nullable: false,
    is_auto: false,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'text',
  },
  {
    key: 'old_value',
    label: 'Old Value',
    type: 'dict',
    nullable: true,
    is_auto: false,
    is_primary_key: false,
    filterable: false,
    has_foreign_key: false,
    field_type: 'textarea',
  },
  {
    key: 'new_value',
    label: 'New Value',
    type: 'dict',
    nullable: true,
    is_auto: false,
    is_primary_key: false,
    filterable: false,
    has_foreign_key: false,
    field_type: 'textarea',
  },
  {
    key: 'performed_at',
    label: 'Performed At',
    type: 'datetime',
    nullable: false,
    is_auto: true,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'datetime',
  },
  {
    key: 'performed_by',
    label: 'Performed By',
    type: 'str',
    nullable: false,
    is_auto: false,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'text',
  },
  {
    key: 'created_at',
    label: 'Created At',
    type: 'datetime',
    nullable: false,
    is_auto: true,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'datetime',
  },
  {
    key: 'updated_at',
    label: 'Updated At',
    type: 'datetime',
    nullable: false,
    is_auto: true,
    is_primary_key: false,
    filterable: true,
    has_foreign_key: false,
    field_type: 'datetime',
  },
];

export const auditLogConfig: EntityConfig = {
  name: 'AuditLog',
  tableName: 'audit_logs',
  prismaModel: 'AuditLog',
  apiPrefix: '/audit-logs',
  tags: ['audit-logs'],
  readonly: true,
  softDelete: false,
  bulkOperations: false,
  columnNames: [
    'id',
    'table_name',
    'record_id',
    'action',
    'old_value',
    'new_value',
    'performed_at',
    'performed_by',
    'created_at',
    'updated_at',
  ],
  searchableFields: ['table_name', 'record_id', 'performed_by', 'action'],
  fields,
  schema: AuditLogSchema,
  createSchema: CreateAuditLogSchema,
  updateSchema: UpdateAuditLogSchema,
};

EntityRegistry.register(auditLogConfig);
