-- name: Get__ENTITY_PASCAL__ :one
SELECT __SELECT_COLS__
FROM __TABLE_NAME__
WHERE id = $1 __SOFT_DELETE_FILTER__;

-- name: List__ENTITY_PASCAL__ :many
SELECT __SELECT_COLS__
FROM __TABLE_NAME__
WHERE 1=1 __SOFT_DELETE_FILTER_AND__
ORDER BY created_at DESC
LIMIT $1 OFFSET $2;

-- name: Count__ENTITY_PASCAL__ :one
SELECT COUNT(*) FROM __TABLE_NAME__
WHERE 1=1 __SOFT_DELETE_FILTER_AND__;
