CREATE TABLE IF NOT EXISTS __TABLE_NAME__ (
    id          UUID PRIMARY KEY,
__MIGRATION_COLUMNS__
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()__SOFT_DELETE_COLUMN__
);

__SOFT_DELETE_INDEX__
